#!/usr/bin/env python3
"""
Interactive R2 Setup Script
Helps you configure R2 storage step by step
"""

import os

def create_env_file():
    """Create .env file with R2 configuration"""
    print("🚀 R2 Configuration Setup")
    print("=" * 40)
    
    print("\n📋 Please provide your R2 credentials:")
    print("(You can find these in your Cloudflare dashboard → R2 → API tokens)")
    
    # Collect information
    print("\n1️⃣ Account ID:")
    print("   Find this in your Cloudflare R2 dashboard (right sidebar)")
    account_id = input("   Enter your Cloudflare Account ID: ").strip()
    
    print("\n2️⃣ API Credentials:")
    print("   Create an API token with 'Object Read & Write' permissions")
    access_key = input("   Enter your R2 Access Key ID: ").strip()
    secret_key = input("   Enter your R2 Secret Access Key: ").strip()
    
    print("\n3️⃣ Bucket Name:")
    bucket_name = input("   Enter your R2 bucket name (default: csv-converter-storage): ").strip()
    if not bucket_name:
        bucket_name = "csv-converter-storage"
    
    print("\n4️⃣ Database Configuration:")
    print("   Do you want to use your Neon PostgreSQL database?")
    use_neon = input("   Use Neon PostgreSQL? (y/n, default: y): ").strip().lower()
    
    database_url = ""
    if use_neon != 'n':
        database_url = "postgresql://neondb_owner:npg_IO2PHryK6lBo@ep-nameless-art-aeo7798p-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require"
    
    # Generate endpoint URL
    endpoint_url = f"https://{account_id}.r2.cloudflarestorage.com"
    
    # Create .env content
    env_content = f"""# CSV Converter API Configuration
# Generated by setup_r2.py

# Environment
ENVIRONMENT=development
DEBUG=true

# R2 Cloud Storage Configuration
USE_CLOUD_STORAGE=true
R2_ENDPOINT_URL={endpoint_url}
R2_ACCESS_KEY_ID={access_key}
R2_SECRET_ACCESS_KEY={secret_key}
R2_BUCKET_NAME={bucket_name}
R2_REGION=auto

# Database Configuration
"""
    
    if database_url:
        env_content += f"DATABASE_URL={database_url}\n"
    else:
        env_content += "DATABASE_PATH=metadata.db\n"
    
    env_content += """
# Authentication
JWT_SECRET_KEY=your-super-secure-secret-key-change-this-in-production
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=10080

# Server Configuration  
HOST=0.0.0.0
PORT=8000
RELOAD=true

# CORS Configuration
CORS_ORIGINS=http://localhost:3000,http://localhost:3001

# File Processing
MAX_FILE_SIZE=104857600
PROCESSING_DELAY_SECONDS=3
"""
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        
        print("\n✅ .env file created successfully!")
        print(f"📁 Location: {os.path.abspath('.env')}")
        
        # Show summary
        print("\n📊 Configuration Summary:")
        print(f"   R2 Endpoint: {endpoint_url}")
        print(f"   R2 Bucket: {bucket_name}")
        print(f"   Access Key: {access_key[:8]}***")
        print(f"   Database: {'Neon PostgreSQL' if database_url else 'Local SQLite'}")
        
        # Next steps
        print("\n🚀 Next Steps:")
        print("1. Make sure your R2 bucket exists in Cloudflare dashboard")
        print("2. Test the configuration: python test_r2_debug.py")
        print("3. Start your API: python run.py")
        print("4. Test file upload via the API or Swagger docs")
        
        return True
        
    except Exception as e:
        print(f"\n❌ Error creating .env file: {str(e)}")
        return False

def check_bucket_instructions():
    """Show instructions for creating R2 bucket"""
    print("\n📦 R2 Bucket Setup Instructions:")
    print("=" * 40)
    print("1. Go to https://dash.cloudflare.com")
    print("2. Navigate to R2 Object Storage")
    print("3. Click 'Create bucket'")
    print("4. Enter bucket name (e.g., csv-converter-storage)")
    print("5. Select region: Automatic (recommended)")
    print("6. Click 'Create bucket'")
    print("\n✅ Your bucket will be ready in a few seconds!")

def main():
    """Main setup flow"""
    print("Welcome to R2 Storage Setup!")
    print("This script will help you configure Cloudflare R2 for your CSV converter.\n")
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("⚠️ .env file already exists!")
        overwrite = input("Do you want to overwrite it? (y/n): ").strip().lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    # Show bucket instructions
    print("\n📋 Before we start, make sure you have:")
    print("✅ A Cloudflare account")
    print("✅ R2 storage enabled")
    print("✅ An R2 bucket created")
    print("✅ R2 API token with Object Read & Write permissions")
    
    show_instructions = input("\nNeed help creating a bucket? (y/n): ").strip().lower()
    if show_instructions == 'y':
        check_bucket_instructions()
        input("\nPress Enter when your bucket is ready...")
    
    # Create configuration
    if create_env_file():
        print("\n🎉 Setup completed successfully!")
        print("Your CSV converter is now configured with R2 cloud storage!")
    else:
        print("\n❌ Setup failed. Please try again.")

if __name__ == "__main__":
    main() 